name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: dist
          user_name: 'github-actions[bot]'  # GitHub Actions bot
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: gh-pages
